Amod Marathe

PRN - 25070123073

exp 9 - Study of Numpy library


In [3]:
#declaration of Numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [7]:
# dimension of Array
print(a.ndim)
print(b.ndim)


#size of matrix \
print(a.size)
print(b.size)
# shape of matrix
a.shape
b.shape

1
2
7
6


(2, 3)

In [12]:
a.dtype
b.dtype

dtype('int64')

In [15]:


# In-Built functions using Numpy
np.zeros((2,3))
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [28]:
print(b*2)
print(a+5)
#print(c)
#print(d)

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [29]:
# addition of scalar matrix
a + 5

array([  6,  15,  25,  35,  45,  55, 505])

In [30]:
# mean of matrix
np.mean(a)

np.float64(93.0)

In [31]:
# median of matrix
np.median(a)


np.float64(30.0)

In [32]:
# sum of matrix
np.sum(a)


np.int64(651)

In [33]:
np.max(a)

np.int64(500)

In [34]:
np.min(a)

np.int64(1)